export const DEFAULT_QUESTIONS = [
  //
  { name: '吉伊卡哇的周邊', min: 1, max: 3, unit: '個' },
  { name: '有公司 logo 的物品', min: 3, max: 6, unit: '個' },
  { name: '有貓咪圖示或造型的物品', min: 2, max: 5, unit: '件' },
  { name: '有狗狗圖示或造型的物品', min: 2, max: 5, unit: '件' },
  //
  { name: '雨傘', min: 3, max: 6, unit: '把' },
  { name: '眼鏡', min: 3, max: 6, unit: '副' },
  { name: '耳機', min: 3, max: 5, unit: '副' },
  { name: '手環', min: 3, max: 5, unit: '條' },
  { name: '圍巾', min: 2, max: 4, unit: '條' },
  { name: '護唇膏或口紅', min: 2, max: 4, unit: '支' },
  { name: '手機', min: 5, max: 8, unit: '部' },
  { name: '鑰匙', min: 8, max: 14, unit: '把' },
  { name: '筆', min: 3, max: 5, unit: '支' },
  { name: '鞋子', min: 2, max: 4, unit: '隻' },
  { name: '手錶', min: 3, max: 5, unit: '支' },
  { name: '帽子', min: 3, max: 4, unit: '頂' },
  { name: '項鍊', min: 3, max: 5, unit: '條' },
  { name: '戒指', min: 3, max: 6, unit: '枚' },
  { name: '錢包或皮夾', min: 3, max: 5, unit: '個' },
  { name: '悠遊卡或交通卡', min: 4, max: 6, unit: '張' },
  { name: '行動電源', min: 2, max: 4, unit: '個' },
  { name: '鑰匙圈', min: 3, max: 5, unit: '副' },
  { name: '香水', min: 1, max: 3, unit: '瓶' },
  { name: '手套', min: 3, max: 5, unit: '隻' },
  { name: '任意相同的 logo', min: 2, max: 3, unit: '個' },
  //
  { name: '右手大拇指', min: 4, max: 7, unit: '隻' },
  { name: '左手大拇指', min: 4, max: 7, unit: '隻' },
]
